apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: adhoc
  labels:
    app: client
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: endpoints-reader
      containers:
        - name: client
          image: client:v1
